version: '3.6'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_DATABASE: reportserver
            MYSQL_USER: reportserver
            MYSQL_PASSWORD: 641949548825f1f8c51d5f547ab88faa
            MYSQL_RANDOM_ROOT_PASSWORD : 'true'
    reportserver:        
        image: ${DOCKERHUB_USER}/reportserver:3.2
        container_name: reportserver
        environment:
            MYSQL_DATABASE: reportserver
            MYSQL_USER: reportserver
            MYSQL_PASSWORD: 641949548825f1f8c51d5f547ab88faa
        ports:
            - "8080:8080"
        depends_on:
            - mysql
